### ISSUE TITLE
Support for Laravel 7 & 8

### ISSUE THREAD

**Issue by MichaelHoughton** [srmklive/laravel-twofactor-authentication#12]
Hi There

If I submit a PR, are you happy to upgrade this package for Laravel 7 and 8 support?

**Comment by srmklive** [comment]
Hi,

Please do.

**Comment by srmklive** [comment]
Hi,

No need, i will publish a new release to support Laravel 7 & 8.

**Comment by MichaelHoughton** [comment]
Thanks so much - ping me if you need me to do a PR, otherwise I will look for the update.

**Comment by srmklive** [comment]
Hi,

I just tagged a new release with support for Laravel 7 & 8.
