### ISSUE TITLE
Usage walkthrough / documentation

### ISSUE THREAD

**Issue by Dynamo6Dev** [srmklive/laravel-twofactor-authentication#6]
Hi, do you have any more detailed documentation of the Usage process? I've followed the README and I have everything installed correctly, but I've hit a wall at the Usage section. The README doesn't say where the API call code should be placed i.e. which files need to be updated. Any help would be much appreciated. Thank you

**Comment by srmklive** [comment]
Hi,

Have a look at the demo app i have created [here](https://github.com/srmklive/laravel-2fa-demo). This should be a good starting point for you. The working link for the demo app is:

https://laravel-2fa.srmk.info/

**Comment by Dynamo6Dev** [comment]
Hi Raza, Thanks for your reply. I had a look at that link but its throwing a DB error when I try and use the register form so I'm not able to get through to the 2FA setup part. Kind regards, Mike

**Comment by srmklive** [comment]
@Dynamo6 You just need to clone the demo application from github, and follow the instructions accordingly. Also i haven't updated the README as well :rofl:.
