### ISSUE TITLE
Adding a custom provider

### ISSUE THREAD

**Issue by georgeboot** [srmklive/laravel-twofactor-authentication#7]
I added a custom provider as specified in the readme. I only can not figure out how to enable this new provider.

The only reference I can find is https://github.com/srmklive/laravel-twofactor-authentication/blob/master/src/AuthyFacadeAccessor.php#L37 but that seems to only allow the built-in provider. I tried `Authy::setProvider(new MessagebirdAuthProvider());` in my AppServiceProvider but that does not help.

What am I doing wrong?

**Comment by georgeboot** [comment]
Never mind, I figured it out myself.

1. Create a new service as specified in the readme, or copy/past the one supplied (https://github.com/srmklive/laravel-twofactor-authentication/blob/master/src/Services/Authy.php).
2. Add new service to your service container:
```
$this->app->singleton('2fa', function () {
    return new MessagebirdAuthProvider();
});```

**Comment by srmklive** [comment]
@georgeboot Thanks for reporting this bug. I will work on a fix for this asap.
