### ISSUE TITLE
Compatibility with Laravel v5.4 (and lower?) is broken since v0.5.9

### ISSUE THREAD

**Issue by addow** [srmklive/laravel-twofactor-authentication#8]
All calls to `authy()` result in a fatal exception when using the latest version v0.5.9 in Laravel 5.4 (and lower):
```php
Call to undefined function App\Http\Controllers\Auth\AuthController\authy()
```

I assume it is caused by the removal of the `functions.php` file. 

A workaround is available by using the static call to `AuthyFacadeAccessor::getProvider()->...`, but `authy()` is much cleaner of course.

**Comment by srmklive** [comment]
yeah i have removed it. You can simply create a trait amd create `authy` function with the following code:

```
public function authy()
{
    return app('authy');
}
```

**Comment by addow** [comment]
OK, good idea. I noticed the documentation is still referencing `authy()`, even for older versions. Are you sure this is still working?

**Comment by srmklive** [comment]
Updated README. You can use Facade instead of global helper.
