### ISSUE TITLE
Not working with laravel5.8

### ISSUE THREAD

**Issue by anishbangalore** [srmklive/laravel-twofactor-authentication#9]
Is there any option to use srmklive/authy with laravel 5.8? waiting for your valuable advice

regards,
Anish

**Comment by srmklive** [comment]
Hi,

I have tagged a new release supporting Laravel 5.8

**Comment by anishbangalore** [comment]
Dear Friend,

The actual issue with laravel5.8 is this one,

Installation request for srmklive/authy ^0.6.1 -> satisfiable by srmklive/authy[v0.6.1].
    - Conclusion: remove nesbot/carbon 2.19.1
    - Conclusion: don't install nesbot/carbon 2.19.1
    - srmklive/authy v0.6.1 requires nesbot/carbon ~1.2 -> satisfiable by nesbot/carbon[1.10.0, 1.11.0, 1.12.0, 1.13.0, 1.14.0, 1.15.0, 1.16.0, 1.17.0, 1.18.0, 1.19.0, 1.2.0, 1.20.0, 1.21.0, 1.22.0, 1.22.1, 1.23.0, 1.24.0, 1.24.1, 1.24.2, 1.25.0, 1.25.1, 1.25.3, 1.26.0, 1.26.1, 1.26.2, 1.26.3, 1.26.4, 1.26.5, 1.26.6, 1.27.0, 1.28.0, 1.29.0, 1.29.1, 1.29.2, 1.3.0, 1.30.0, 1.31.0, 1.31.1, 1.32.0, 1.33.0, 1.34.0, 1.34.1, 1.34.2, 1.34.3, 1.34.4, 1.35.0, 1.35.1, 1.36.0, 1.36.1, 1.36.2, 1.37.0, 1.37.1, 1.38.0, 1.38.1, 1.38.2, 1.38.3, 1.38.4, 1.4.0, 1.5.0, 1.6.0, 1.7.0, 1.8.0, 1.9.0].
    - Can only install one of: nesbot/carbon[1.26.0, 2.19.1].

there is already a nesbot/carbon with laravel5.8 so I think removing the line "nesbot/carbon": "~1.2" from composer.json or update that line as "nesbot/carbon":"^2.19" may solve the actual issue

thanks and regards,
Anish

**Comment by srmklive** [comment]
You should have described that earlier though. How would i know what dependency was broken or not. Anyways update the package to newest version again. Should be fixed though.

**Comment by anishbangalore** [comment]
Sorry it was my mistake, I had to mention the error when I posted the issue, anyway thanks a lot now it is able to install.

Thanks and regards
